### ISSUE TITLE
Arrow frame

### ISSUE THREAD

**Issue by Zengoth** [guydunigo/BlindQuest_website#2]
When we click on an arrow a frame appears around it to show that is has been selected. But it stays until we click somewhere else.

**Comment by guydunigo** [comment]
It shouldn't be removed as for accessibility matter (keyboard users). (cf : [this article](https://www.tjvantoll.com/2013/01/28/stop-messing-with-the-browsers-default-focus-outline/)). We can provide a custom outline which fits better with the whole website though (it has to be easily seen).
